import struct
import numpy as np
import sys

def load_ascii_vector(file_name, var_name=None):
    vector = np.asarray(np.loadtxt(file_name), dtype=np.float32)
    return vector


def write_user_feat(x, name='filename'):
    period = 100000 # assumes 0.010 ms frame shift
    dim_num = x.shape[0]
    number_frames = x.shape[1]
    hdr = struct.pack(
        '>iihh',  ##'>' says write big-endian
        number_frames,  # Samples
        period,  # samplePeriod
        4*dim_num,  # 2 floats per feature
        9)  # user features

    output_file = open(name, 'wb')
    output_file.write(hdr)

    for t in range(0, number_frames):
        f = np.array(x[:,t],'f')
        if sys.byteorder == 'little':
            f.byteswap(True)
        f.tofile(output_file)

    output_file.close()

def read_user_feat(file_name='filename'):
    f = open(file_name,'rb')
    hdr = f.read(12)
    number_samples, sample_period, sample_size, parm_kind = struct.unpack(">IIHH", hdr)
    if parm_kind != 9:
        raise RuntimeError(' error : in reading file not generated by us\n')

    dim_num = sample_size//4

    features = np.zeros([number_samples, dim_num],dtype=float)
    for t in range(number_samples):
        features[t,:] = np.array(struct.unpack('>' + ('f' * dim_num), f.read(sample_size)),dtype=float)

    return features


def write_stats(x,file_name='filename'):
    output_file = open(file_name,'w')
    for t in range(0, x.shape[0]):
        output_file.write("{0}\n".format(x[t]))
    output_file.close()